export default {
    DICTIONARY: 'DICTIONARY',
    PRODUCT_DROPDOWN_LIST: 'PRODUCT_DROPDOWN_LIST',
    UNIT_DROPDOWN_LIST: 'UNIT_DROPDOWN_LIST',
    SUPPLIER_DROPDOWN_LIST: 'SUPPLIER_DROPDOWN_LIST',
    //-- Lấy danh sách sản phẩm
    GET_PROD_LIST: 'GET_PROD_LIST',
    //-- Lấy thông tin 1 sản phẩm
    GET_PROD: 'GET_PROD',
    //-- Thêm mới sản phẩm
    INS_PROD: 'INS_PROD',
    //-- Sửa thôngtin sản phẩm
    MOD_PROD: 'MOD_PROD',
    //-- Xóa sản phẩm
    DEL_PROD: 'DEL_PROD',
    //-- Lấy danh sách đơn vị
    GET_UNIT_LIST: 'GET_UNIT_LIST',
    //-- Lấy thông tin 1 đơn vị
    GET_UNIT: 'GET_UNIT',
    //-- Thêm mới đơn vị
    INS_UNIT: 'INS_UNIT',
    //-- Sửa thôngtin đơn vị
    MOD_UNIT: 'MOD_UNIT',
    //-- Xóa đơn vị
    DEL_UNIT: 'DEL_UNIT',

    PRODUCT_GROUP_LIST: 'PRODUCT_GROUP_LIST',
    PRODUCT_GROUP_BY_ID: 'PRODUCT_GROUP_BY_ID',
    PRODUCT_GROUP_ADD: 'PRODUCT_GROUP_ADD',
    PRODUCT_GROUP_UPDATE: 'PRODUCT_GROUP_UPDATE',
    PRODUCT_GROUP_DELETE: 'PRODUCT_GROUP_DELETE',

    PRODUCT_LIST: 'PRODUCT_LIST',
    PRODUCT_BY_ID: 'PRODUCT_BY_ID',
    PRODUCT_ADD: 'PRODUCT_ADD',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_DELETE: 'PRODUCT_DELETE',

    UNIT_RATE_LIST: 'UNIT_RATE_LIST',
    UNIT_RATE_BY_ID: 'UNIT_RATE_BY_ID',
    UNIT_RATE_CREATE: 'UNIT_RATE_CREATE',
    UNIT_RATE_UPDATE: 'UNIT_RATE_UPDATE',
    UNIT_RATE_DELETE: 'UNIT_RATE_DELETE',

    WARN_TIME_LIST: 'WARN_TIME_LIST',
    WARN_TIME_BY_ID: 'WARN_TIME_BY_ID',
    WARN_TIME_CREATE: 'WARN_TIME_CREATE',
    WARN_TIME_UPDATE: 'WARN_TIME_UPDATE',
    WARN_TIME_DELETE: 'WARN_TIME_DELETE',

    PRICE_LIST: 'PRICE_LIST',
    PRICE_BY_ID: 'PRICE_BY_ID',
    PRICE_CREATE: 'PRICE_CREATE',
    PRICE_UPDATE: 'PRICE_UPDATE',
    PRICE_DELETE: 'PRICE_DELETE',

    STORE_LIMIT_LIST: 'STORE_LIMIT_LIST',
    STORE_LIMIT_BY_ID: 'STORE_LIMIT_BY_ID',
    STORE_LIMIT_CREATE: 'STORE_LIMIT_CREATE',
    STORE_LIMIT_UPDATE: 'STORE_LIMIT_UPDATE',
    STORE_LIMIT_DELETE: 'STORE_LIMIT_DELETE',

    CUSTOMER_LIST: 'CUSTOMER_LIST',
    CUSTOMER_BY_ID: 'CUSTOMER_BY_ID',
    CUSTOMER_CREATE: 'CUSTOMER_CREATE',
    CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
    CUSTOMER_DELETE: 'CUSTOMER_DELETE',

    IMPORT_LIST: 'IMPORT_LIST',
    IMPORT_BY_ID: 'IMPORT_BY_ID',
    IMPORT_CREATE: 'IMPORT_CREATE',
    IMPORT_UPDATE: 'IMPORT_UPDATE',
    IMPORT_DELETE: 'IMPORT_DELETE',

    GET_ALL_PRODUCT_BY_INVOICE_ID: 'GET_ALL_PRODUCT_BY_INVOICE_ID',
    PRODUCT_IMPORT_INVOICE_LIST: 'PRODUCT_IMPORT_INVOICE_LIST',
    PRODUCT_IMPORT_INVOICE_BY_ID: 'PRODUCT_IMPORT_INVOICE_BY_ID',
    PRODUCT_IMPORT_INVOICE_CREATE: 'PRODUCT_IMPORT_INVOICE_CREATE',
    PRODUCT_IMPORT_INVOICE_UPDATE: 'PRODUCT_IMPORT_INVOICE_UPDATE',
    PRODUCT_IMPORT_INVOICE_DELETE: 'PRODUCT_IMPORT_INVOICE_DELETE',

    IMPORT_INVENTORY_LIST: 'IMPORT_INVENTORY_LIST',
    IMPORT_INVENTORY_BY_ID: 'IMPORT_INVENTORY_BY_ID',
    IMPORT_INVENTORY_CREATE: 'IMPORT_INVENTORY_CREATE',
    IMPORT_INVENTORY_UPDATE: 'IMPORT_INVENTORY_UPDATE',
    IMPORT_INVENTORY_DELETE: 'IMPORT_INVENTORY_DELETE',

    EXPORT_LIST: 'EXPORT_LIST',
    EXPORT_BY_ID: 'EXPORT_BY_ID',
    EXPORT_CREATE: 'EXPORT_CREATE',
    EXPORT_UPDATE: 'EXPORT_UPDATE',
    EXPORT_DELETE: 'EXPORT_DELETE',

    GET_ALL_PRODUCT_BY_INVOICE_ID: 'GET_ALL_PRODUCT_BY_INVOICE_ID',
    PRODUCT_EXPORT_INVOICE_LIST: 'PRODUCT_EXPORT_INVOICE_LIST',
    PRODUCT_EXPORT_INVOICE_BY_ID: 'PRODUCT_EXPORT_INVOICE_BY_ID',
    PRODUCT_EXPORT_INVOICE_CREATE: 'PRODUCT_EXPORT_INVOICE_CREATE',
    PRODUCT_EXPORT_INVOICE_UPDATE: 'PRODUCT_EXPORT_INVOICE_UPDATE',
    PRODUCT_EXPORT_INVOICE_DELETE: 'PRODUCT_EXPORT_INVOICE_DELETE',
}
